name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso de debug para verificar que los valores están llegando correctamente
      - name: Debug Info
        run: |
          echo "ORG_ID=${{ secrets.VERCEL_ORG_ID }}"
          echo "PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}"
          # NO imprimas el token por seguridad

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm --org ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }}
